### ISSUE TITLE
Access Denied: COM3

### ISSUE THREAD

**Issue by dennisai** [jcurl/SerialPortStream#38]
Hi, I am using Serial Port Stream on .NET 4.5.1 / Windows 10 Pro x64 as a replacement for the default SerialPort implementation in the .NET Framework.  However, when I go to open my port, I get an access denied exception.

     public bool IsConnected
     {
         get {
             if (!isConnected.HasValue) {
                mutex.WaitOne();
                if (!serialPortStream.IsOpen) { serialPortStream.Open(); } // Exception thrown here.
                ...
             }
        }
    }

The stack trace is as follows.

     at RJCP.IO.Ports.Native.WinNativeSerial.WinIOError() in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\Native\WinNativeSerial.cs:line 937
     at RJCP.IO.Ports.Native.WinNativeSerial.Open() in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\Native\WinNativeSerial.cs:line 845
     at RJCP.IO.Ports.SerialPortStream.Open(Boolean setCommState) in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\SerialPortStream.cs:line 245

Any idea why this might be happening?  The implementation I was using before with the SerialPort from .NET Framework was working fine, and I can open the port using Advanced Serial Port Monitor with no problems.

This is the serial port in Device Manager.
![serialport](https://user-images.githubusercontent.com/1017972/31242291-60b295ea-a9bb-11e7-9734-8b4edf3fe536.PNG)

**Comment by dennisai** [comment]
Just to report, I have tried to upgrade to .NET 4.6.2 but to no avail.  Same problem.

**Comment by dennisai** [comment]
Nevermind, this issue came from something else in my code.  Everything works great, and way better than the default SerialPort implementation!
