### ISSUE TITLE
hi in the raspberry pi Raspbian  some time will write problem

### ISSUE THREAD

**Issue by pigwing** [jcurl/SerialPortStream#63]
"stackTrace": "   at RJCP.IO.Ports.SerialPortStream.WriteCheckDeviceError()
	\n   at RJCP.IO.Ports.SerialPortStream.WriteCheck(Byte[] buffer, Int32 offset, Int32 count)
	\n   at RJCP.IO.Ports.SerialPortStream.Write(Byte[] buffer, Int32 offset, Int32 count)
in this time i must create SerialPortStream port again 
i create the serial port once and not close the port until app close

**Comment by jcurl** [comment]
For some reason the main thread died (a critical error). The system won't recover in this case. See the code here:

```
        private void WriteCheckDeviceError()
        {
            if (m_Buffer != null) {
                if (IsOpen && !m_NativeSerial.IsRunning) {
                    throw new System.IO.IOException("Device Error");
                }
            }
        }
```

You should enable tracing and look what was reported why the thread died. See the Wiki: https://github.com/jcurl/SerialPortStream/wiki/Tracing
