### ISSUE TITLE
Unsupported baud rate error on Raspberry4

### ISSUE THREAD

**Issue by ningjx** [jcurl/SerialPortStream#98]
errormessage:[Unsupported baud rate (0; Invalid argument)] while init with baud rate 100000,but 115200 is ok

**Comment by ningjx** [comment]
at RJCP.IO.Ports.Native.UnixNativeSerial.ThrowException()
   at RJCP.IO.Ports.Native.UnixNativeSerial.set_BaudRate(Int32 value)
   at RJCP.IO.Ports.SerialPortStream.set_BaudRate(Int32 value)

**Comment by jcurl** [comment]
I would expect the behaviour specified. Libnserial uses standard Linux STTY code and polls for particular baudrates. If there are other baudrates not being checked by the build system (such as 100k) but is defined by your OS, libnserial needs to be patched.
